using System;

/// <summary>
/// Summary description for tapVoucherCExGst
/// </summary>
public class tapVoucherCExGst
{
    public int? iLote { get; set; }
    public int? vKey { get; set; }
    public int? iApplySeqNo { get; set; }
    public int? iBatchKey { get; set; }
    public int? iRemitToVendAddrKey { get; set; }
    public string iRemitToVendAddrID { get; set; }
    public int? iRemitToCopyKey { get; set; }
    public string iRemitToCopyID { get; set; }
    public string iRemitToAddrName { get; set; }
    public string iRTAddrLine1 { get; set; }
    public string iRTAddrLine2 { get; set; }
    public string iRTAddrLine3 { get; set; }
    public string iRTAddrLine4 { get; set; }
    public string iRTAddrLine5 { get; set; }
    public string iRTCity { get; set; }
    public string iRTState { get; set; }
    public string iRTCountryID { get; set; }
    public string iRTPostalCode { get; set; }
    public int? iCashAcctKey { get; set; }
    public string iCashAcctID { get; set; }
    public int? iCntcKey { get; set; }
    public string iCntcName { get; set; }
    public double? iCurrExchRate { get; set; }
    public int? iCurrExchSchdKey { get; set; }
    public string iCurrExchSchdID { get; set; }
    public string iCurrID { get; set; }
    public short iHoldPmt { get; set; }
    public int? iVendClassKey { get; set; }
    public string iVendClassID { get; set; }
    public int? iVendKey { get; set; }
    public string iVendID { get; set; }
    public int? iFOBKey { get; set; }
    public string iFOBID { get; set; }
    public int? iImportLogKey { get; set; }
    public int? iPmtTermsKey { get; set; }
    public string iPmtTermsID { get; set; }
    public int? iReasonCodeKey { get; set; }
    public string iReasonCodeID { get; set; }
    public decimal? iFreightAmt { get; set; }
    public short iSeparateCheck { get; set; }
    public int? iShipMethKey { get; set; }
    public string iShipMethID { get; set; }
    public int? iPurchFromVendAddrKey { get; set; }
    public string iPurchFromVendAddrID { get; set; }
    public int? iPurchToCopyKey { get; set; }
    public string iPurchToCopyID { get; set; }
    public string iPurchFromAddrName { get; set; }
    public string iPurchAddrLine1 { get; set; }
    public string iPurchAddrLine2 { get; set; }
    public string iPurchAddrLine3 { get; set; }
    public string iPurchAddrLine4 { get; set; }
    public string iPurchAddrLine5 { get; set; }
    public string iPurchCity { get; set; }
    public string iPurchState { get; set; }
    public string iPurchCountryID { get; set; }
    public string iPurchPostalCode { get; set; }
    public int? iShipZoneKey { get; set; }
    public string iShipZoneID { get; set; }
    public string iTranCmnt { get; set; }
    public DateTime? iTranDate { get; set; }
    public string iTranNo { get; set; }
    public int? iTranType { get; set; }
    public string iUniqueID { get; set; }
    public short iDefaultIfNull { get; set; }
    public string iUserID { get; set; }
    public string iV1099Box { get; set; }
    public string iV1099BoxText { get; set; }
    public short iV1099Form { get; set; }
    public decimal? iRetntAmt { get; set; }
    public string iVouchNo { get; set; }
    public DateTime? iInvcRcptDate { get; set; }
    public int? oVouchKey { get; set; }
    public string oTranID { get; set; }
    public DateTime? iDueDate { get; set; }
    public decimal? iDiscAmt { get; set; }
    public DateTime? iDiscDate { get; set; }
    public int? iExemptKey { get; set; }
    public decimal? iSTaxAmt { get; set; }
    public decimal? iPurchAmt { get; set; }
    public decimal? iTranAmt { get; set; }
    public int? oRetVal { get; set; }
}