//PORTAL DE PROVEDORES T|SYS|
//10 DE ENERO, 2019
//DESARROLLADO POR MULTICONSULTING S.A. DE C.V.
//ACTUALIZADO POR : ADRIAN QUIALA

//REFERENCIAS UTILIZADAS
using System;

public class HttpPostAttribute : Attribute
{
}