//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proveedores_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccessLog
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AccessLog()
        {
            this.ErrorLog = new HashSet<ErrorLog>();
        }
    
        public int LogKey { get; set; }
        public int UserKey { get; set; }
        public System.DateTime LoginDate { get; set; }
        public string CompanyID { get; set; }
        public string IP { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual Users Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ErrorLog> ErrorLog { get; set; }
    }
}
namespace Proveedores_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Applications
    {
        public System.Guid ApplicationId { get; set; }
        public string ApplicationName { get; set; }
        public string Description { get; set; }
    }
}
namespace Proveedores_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetRoles
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AspNetRoles()
        {
            this.AspNetUsers = new HashSet<AspNetUsers>();
        }
    
        public string Id { get; set; }
        public string Name { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetUsers> AspNetUsers { get; set; }
    }
}
namespace Proveedores_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetUserClaims
    {
        public int Id { get; set; }
        public string UserId { get; set; }
        public string ClaimType { get; set; }
        public string ClaimValue { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
    }
}
namespace Proveedores_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetUserLogins
    {
        public string LoginProvider { get; set; }
        public string ProviderKey { get; set; }
        public string UserId { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
    }
}
namespace Proveedores_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetUsers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AspNetUsers()
        {
            this.AspNetUserClaims = new HashSet<AspNetUserClaims>();
            this.AspNetUserLogins = new HashSet<AspNetUserLogins>();
            this.AspNetRoles = new HashSet<AspNetRoles>();
        }
    
        public string Id { get; set; }
        public Nullable<int> UserKey { get; set; }
        public string Email { get; set; }
        public bool EmailConfirmed { get; set; }
        public string PasswordHash { get; set; }
        public string SecurityStamp { get; set; }
        public string PhoneNumber { get; set; }
        public bool PhoneNumberConfirmed { get; set; }
        public bool TwoFactorEnabled { get; set; }
        public Nullable<System.DateTime> LockoutEndDateUtc { get; set; }
        public bool LockoutEnabled { get; set; }
        public int AccessFailedCount { get; set; }
        public string UserName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetUserClaims> AspNetUserClaims { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetUserLogins> AspNetUserLogins { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetRoles> AspNetRoles { get; set; }
    }
}
namespace Proveedores_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class C__MigrationHistory
    {
        public string MigrationId { get; set; }
        public string ContextKey { get; set; }
        public byte[] Model { get; set; }
        public string ProductVersion { get; set; }
    }
}
namespace Proveedores_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CheckRequest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CheckRequest()
        {
            this.ChkReqDetail = new HashSet<ChkReqDetail>();
            this.ChkReqFile = new HashSet<ChkReqFile>();
        }
    
        public int ChkReqKey { get; set; }
        public int UserKey { get; set; }
        public int VendorKey { get; set; }
        public string CompanyID { get; set; }
        public string Serie { get; set; }
        public System.DateTime ChkReqDate { get; set; }
        public Nullable<System.DateTime> ChkReqPmtDate { get; set; }
        public string PmtTerms { get; set; }
        public Nullable<decimal> Total { get; set; }
        public string Concept { get; set; }
        public string Comment { get; set; }
        public string Moneda { get; set; }
        public Nullable<int> ApplInvcRcptKey { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<bool> Cancelado { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int CreateUserkey { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<int> UpdateUserKey { get; set; }
        public Nullable<int> UpdateCounter { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual Users Users { get; set; }
        public virtual Users Users1 { get; set; }
        public virtual Users Users2 { get; set; }
        public virtual Vendors Vendors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChkReqDetail> ChkReqDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChkReqFile> ChkReqFile { get; set; }
    }
}
namespace Proveedores_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChkReqDetail
    {
        public int ChkReqKey { get; set; }
        public int VendorKey { get; set; }
        public int InvcRcptKey { get; set; }
        public Nullable<int> VoucherKey { get; set; }
        public string Tipo { get; set; }
        public string VoucherNo { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<int> Counter { get; set; }
        public Nullable<int> ChkReqLine { get; set; }
        public int ChkReqDetailKey { get; set; }
    
        public virtual CheckRequest CheckRequest { get; set; }
        public virtual InvoiceReceipt InvoiceReceipt { get; set; }
        public virtual Vendors Vendors { get; set; }
        public virtual Voucher Voucher { get; set; }
    }
}
namespace Proveedores_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChkReqFile
    {
        public int ChkReqFileKey { get; set; }
        public int CheckRequestKey { get; set; }
        public string FileType { get; set; }
        public byte[] FileBinary { get; set; }
    
        public virtual CheckRequest CheckRequest { get; set; }
    }
}
namespace Proveedores_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Company()
        {
            this.AccessLog = new HashSet<AccessLog>();
            this.CheckRequest = new HashSet<CheckRequest>();
            this.Documents = new HashSet<Documents>();
            this.ErrorLog = new HashSet<ErrorLog>();
            this.Invoice = new HashSet<Invoice>();
            this.InvoiceReceipt = new HashSet<InvoiceReceipt>();
            this.Payment = new HashSet<Payment>();
            this.UsersInCompany = new HashSet<UsersInCompany>();
            this.Vendors = new HashSet<Vendors>();
        }
    
        public string CompanyID { get; set; }
        public string CompanyName { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<int> CreateUserKey { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<int> UpdateUserKey { get; set; }
        public int Status { get; set; }
        public string LetraFolios { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccessLog> AccessLog { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CheckRequest> CheckRequest { get; set; }
        public virtual Users Users { get; set; }
        public virtual Users Users1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Documents> Documents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ErrorLog> ErrorLog { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Invoice> Invoice { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvoiceReceipt> InvoiceReceipt { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payment> Payment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsersInCompany> UsersInCompany { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vendors> Vendors { get; set; }
    }
}
namespace Proveedores_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Documents
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Documents()
        {
            this.DocumentsFile = new HashSet<DocumentsFile>();
        }
    
        public int DocKey { get; set; }
        public string DocID { get; set; }
        public string DocDescription { get; set; }
        public int VendorKey { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int CreateUserKey { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<int> UpdateUserKey { get; set; }
        public string CompanyID { get; set; }
        public Nullable<int> Status { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual Users Users { get; set; }
        public virtual Users Users1 { get; set; }
        public virtual Vendors Vendors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentsFile> DocumentsFile { get; set; }
    }
}
namespace Proveedores_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentsFile
    {
        public int DocKey { get; set; }
        public string DocID { get; set; }
        public byte[] DocFile { get; set; }
        public string FileType { get; set; }
    
        public virtual Documents Documents { get; set; }
    }
}
namespace Proveedores_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ErrorLog
    {
        public int ErrorKey { get; set; }
        public int UserKey { get; set; }
        public int LogKey { get; set; }
        public System.DateTime ErrorDate { get; set; }
        public string Proceso { get; set; }
        public string Message { get; set; }
        public string CompanyID { get; set; }
    
        public virtual AccessLog AccessLog { get; set; }
        public virtual Company Company { get; set; }
        public virtual Users Users { get; set; }
    }
}
namespace Proveedores_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvcRcptDetails
    {
        public int InvcRcptKey { get; set; }
        public int InvoiceKey { get; set; }
        public string UUID { get; set; }
        public string Folio { get; set; }
        public string Tipo { get; set; }
        public string Moneda { get; set; }
        public decimal IVA { get; set; }
        public decimal ISR { get; set; }
        public decimal TotalTax { get; set; }
        public decimal Total { get; set; }
        public int InvcRcptDetailsKey { get; set; }
    
        public virtual Invoice Invoice { get; set; }
        public virtual InvoiceReceipt InvoiceReceipt { get; set; }
    }
}
namespace Proveedores_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvcRcptFile
    {
        public int InvcRcptkey { get; set; }
        public byte[] FileBinary { get; set; }
        public string FileType { get; set; }
        public string Counter { get; set; }
        public int InvcRcptFileKey { get; set; }
    
        public virtual InvoiceReceipt InvoiceReceipt { get; set; }
    }
}
namespace Proveedores_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Invoice()
        {
            this.InvcRcptDetails = new HashSet<InvcRcptDetails>();
            this.Invoice1 = new HashSet<Invoice>();
            this.InvoiceLines = new HashSet<InvoiceLines>();
        }
    
        public int InvoiceKey { get; set; }
        public int VendorKey { get; set; }
        public string RFCEmisor { get; set; }
        public string RFCReceptor { get; set; }
        public string NombreEmisor { get; set; }
        public string NombreReceptor { get; set; }
        public string Folio { get; set; }
        public string Serie { get; set; }
        public string NodeOc { get; set; }
        public string UUID { get; set; }
        public Nullable<System.DateTime> FechaTransaccion { get; set; }
        public Nullable<System.DateTime> FechaTimbrado { get; set; }
        public string Moneda { get; set; }
        public string UsoCFDi { get; set; }
        public string TipoComprobante { get; set; }
        public string FormaPago { get; set; }
        public string MetodoPago { get; set; }
        public Nullable<decimal> ImpuestoImporteTrs { get; set; }
        public Nullable<decimal> ImpuestoImporteRtn { get; set; }
        public Nullable<decimal> Descuento { get; set; }
        public decimal Subtotal { get; set; }
        public decimal Total { get; set; }
        public Nullable<bool> Cancelado { get; set; }
        public Nullable<bool> Timbrado { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> AprovDate { get; set; }
        public string AprovUserKey { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<int> UpdateUserKey { get; set; }
        public string CompanyID { get; set; }
        public Nullable<int> ApplyToInvcKey { get; set; }
        public string TranType { get; set; }
    
        public virtual Company Company { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvcRcptDetails> InvcRcptDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Invoice> Invoice1 { get; set; }
        public virtual Invoice Invoice2 { get; set; }
        public virtual Vendors Vendors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvoiceLines> InvoiceLines { get; set; }
    }
}
namespace Proveedores_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceFile
    {
        public int InvcFileKey { get; set; }
        public Nullable<int> InvoiceKey { get; set; }
        public Nullable<int> VendorKey { get; set; }
        public byte[] FileBinary1 { get; set; }
        public byte[] FileBinary2 { get; set; }
        public byte[] FileBinary3 { get; set; }
        public byte[] FileBinary4 { get; set; }
        public string FileType1 { get; set; }
        public string FileType2 { get; set; }
        public string FileType3 { get; set; }
        public string FileType4 { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<int> UpdateUserKey { get; set; }
        public string CompanyId { get; set; }
    }
}
namespace Proveedores_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceLines
    {
        public int InvoiceLineKey { get; set; }
        public int InvoiceKey { get; set; }
        public string Codigo { get; set; }
        public string ClaveProd { get; set; }
        public string ClaveUni { get; set; }
        public string Unidad { get; set; }
        public string Descripcion { get; set; }
        public Nullable<decimal> ValorUnitario { get; set; }
        public Nullable<decimal> Cantidad { get; set; }
        public Nullable<decimal> Importe { get; set; }
        public Nullable<decimal> Descuento { get; set; }
        public Nullable<int> status { get; set; }
    
        public virtual Invoice Invoice { get; set; }
    }
}
namespace Proveedores_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceReceipt
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InvoiceReceipt()
        {
            this.ChkReqDetail = new HashSet<ChkReqDetail>();
            this.InvcRcptDetails = new HashSet<InvcRcptDetails>();
            this.InvcRcptFile = new HashSet<InvcRcptFile>();
        }
    
        public int InvcRcptKey { get; set; }
        public int UserKey { get; set; }
        public int VendorKey { get; set; }
        public string CompanyID { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int CreateUserKey { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public int UpdateUserKey { get; set; }
        public string Folio { get; set; }
        public System.DateTime RcptDate { get; set; }
        public System.DateTime PaymentDate { get; set; }
        public string PaymentTerms { get; set; }
        public decimal Total { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<bool> Cancelado { get; set; }
        public Nullable<bool> Approved { get; set; }
        public string Comment { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChkReqDetail> ChkReqDetail { get; set; }
        public virtual Company Company { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvcRcptDetails> InvcRcptDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvcRcptFile> InvcRcptFile { get; set; }
        public virtual Users Users { get; set; }
        public virtual Users Users1 { get; set; }
        public virtual Users Users2 { get; set; }
        public virtual Vendors Vendors { get; set; }
    }
}
namespace Proveedores_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceTaxLine
    {
        public int TaxLineKey { get; set; }
        public int InvoiceLineKey { get; set; }
        public int InvoiceKey { get; set; }
        public Nullable<decimal> TaxAmt { get; set; }
        public string TaxID { get; set; }
        public Nullable<decimal> rate { get; set; }
        public string Tipo { get; set; }
        public Nullable<short> Status { get; set; }
    }
}
namespace Proveedores_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Memberships
    {
        public System.Guid UserId { get; set; }
        public System.Guid ApplicationId { get; set; }
        public string Password { get; set; }
        public int PasswordFormat { get; set; }
        public string PasswordSalt { get; set; }
        public string Email { get; set; }
        public string PasswordQuestion { get; set; }
        public string PasswordAnswer { get; set; }
        public bool IsApproved { get; set; }
        public bool IsLockedOut { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime LastLoginDate { get; set; }
        public System.DateTime LastPasswordChangedDate { get; set; }
        public System.DateTime LastLockoutDate { get; set; }
        public int FailedPasswordAttemptCount { get; set; }
        public System.DateTime FailedPasswordAttemptWindowStart { get; set; }
        public int FailedPasswordAnswerAttemptCount { get; set; }
        public System.DateTime FailedPasswordAnswerAttemptWindowsStart { get; set; }
        public string Comment { get; set; }
    }
}
namespace Proveedores_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Payment()
        {
            this.PaymentAppl = new HashSet<PaymentAppl>();
        }
    
        public int PaymentKey { get; set; }
        public int VendorKey { get; set; }
        public string CompanyID { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int CreateUserKey { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<int> UpdateUserKey { get; set; }
        public System.DateTime PaymentDate { get; set; }
        public string PaymendDateTimb { get; set; }
        public string UUID { get; set; }
        public string Serie { get; set; }
        public string Folio { get; set; }
        public Nullable<decimal> Subtotal { get; set; }
        public decimal Total { get; set; }
        public Nullable<System.DateTime> AprovDate { get; set; }
        public Nullable<int> AprovUserKey { get; set; }
        public Nullable<bool> Cancelado { get; set; }
        public int Status { get; set; }
        public Nullable<double> Version { get; set; }
        public Nullable<int> UpdateCounter { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual Users Users { get; set; }
        public virtual Users Users1 { get; set; }
        public virtual Vendors Vendors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaymentAppl> PaymentAppl { get; set; }
        public virtual PaymentFile PaymentFile { get; set; }
    }
}
namespace Proveedores_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentAppl
    {
        public int PaymentKey { get; set; }
        public string ApplUUID { get; set; }
        public string ApplSerie { get; set; }
        public string ApplFolio { get; set; }
        public Nullable<decimal> PaymtApplied { get; set; }
        public Nullable<int> PartialNumber { get; set; }
        public Nullable<decimal> BalanceAnt { get; set; }
        public Nullable<decimal> BalanceOut { get; set; }
        public string Moneda { get; set; }
        public string FormaPago { get; set; }
        public Nullable<int> ApplInvoiceKey { get; set; }
        public string MetodoPago { get; set; }
    
        public virtual Payment Payment { get; set; }
    }
}
namespace Proveedores_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentFile
    {
        public int PaymentKey { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> CreateUserKey { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<int> UpdateUserKey { get; set; }
        public Nullable<int> VendorKey { get; set; }
        public string CompanyID { get; set; }
        public byte[] FileBinary { get; set; }
        public string FileType { get; set; }
        public Nullable<int> Counter { get; set; }
    
        public virtual Payment Payment { get; set; }
    }
}
namespace Proveedores_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Profiles
    {
        public System.Guid UserId { get; set; }
        public string PropertyNames { get; set; }
        public string PropertyValueStrings { get; set; }
        public byte[] PropertyValueBinary { get; set; }
        public System.DateTime LastUpdatedDate { get; set; }
    }
}
namespace Proveedores_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Roles
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Roles()
        {
            this.UsersInRoles = new HashSet<UsersInRoles>();
        }
    
        public int RoleKey { get; set; }
        public string RoleID { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> CreateUserKey { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsersInRoles> UsersInRoles { get; set; }
    }
}
namespace Proveedores_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SettingsEmail
    {
        public int KeyMail { get; set; }
        public string Usuario { get; set; }
        public string Password { get; set; }
        public string Host { get; set; }
        public Nullable<int> Puerto { get; set; }
        public Nullable<int> TaskAdd { get; set; }
    }
}
namespace Proveedores_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class StatusDocs
    {
        public int Status { get; set; }
        public string Descripcion { get; set; }
    }
}
namespace Proveedores_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class StatusUsers
    {
        public int Status { get; set; }
        public string Descripcion { get; set; }
    }
}
namespace Proveedores_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tapLFStatus
    {
        public int Status { get; set; }
        public string Descripcion { get; set; }
    }
}
namespace Proveedores_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TypeFiles
    {
        public int IdFile { get; set; }
        public Nullable<int> DocKey { get; set; }
        public string Descripcion { get; set; }
        public string DocID { get; set; }
    }
}
namespace Proveedores_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Users()
        {
            this.AccessLog = new HashSet<AccessLog>();
            this.CheckRequest = new HashSet<CheckRequest>();
            this.CheckRequest1 = new HashSet<CheckRequest>();
            this.CheckRequest2 = new HashSet<CheckRequest>();
            this.Company = new HashSet<Company>();
            this.Company1 = new HashSet<Company>();
            this.Documents = new HashSet<Documents>();
            this.Documents1 = new HashSet<Documents>();
            this.ErrorLog = new HashSet<ErrorLog>();
            this.InvoiceReceipt = new HashSet<InvoiceReceipt>();
            this.InvoiceReceipt1 = new HashSet<InvoiceReceipt>();
            this.InvoiceReceipt2 = new HashSet<InvoiceReceipt>();
            this.Payment = new HashSet<Payment>();
            this.Payment1 = new HashSet<Payment>();
            this.UsersInCompany = new HashSet<UsersInCompany>();
            this.UsersInRoles = new HashSet<UsersInRoles>();
            this.Vendors = new HashSet<Vendors>();
        }
    
        public int UserKey { get; set; }
        public string UserID { get; set; }
        public string UserName { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> CreateUserKey { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<int> UpdateUserKey { get; set; }
        public Nullable<int> Status { get; set; }
        public string PasswordHash { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccessLog> AccessLog { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CheckRequest> CheckRequest { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CheckRequest> CheckRequest1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CheckRequest> CheckRequest2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Company> Company { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Company> Company1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Documents> Documents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Documents> Documents1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ErrorLog> ErrorLog { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvoiceReceipt> InvoiceReceipt { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvoiceReceipt> InvoiceReceipt1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvoiceReceipt> InvoiceReceipt2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payment> Payment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payment> Payment1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsersInCompany> UsersInCompany { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsersInRoles> UsersInRoles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vendors> Vendors { get; set; }
    }
}
namespace Proveedores_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersInCompany
    {
        public int UserKey { get; set; }
        public string CompanyID { get; set; }
        public int UsersInCompanyKey { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual Users Users { get; set; }
    }
}
namespace Proveedores_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersInRoles
    {
        public int UserKey { get; set; }
        public int RoleKey { get; set; }
        public int UsersInRolesKey { get; set; }
    
        public virtual Roles Roles { get; set; }
        public virtual Users Users { get; set; }
    }
}
namespace Proveedores_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vendors
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vendors()
        {
            this.CheckRequest = new HashSet<CheckRequest>();
            this.ChkReqDetail = new HashSet<ChkReqDetail>();
            this.Documents = new HashSet<Documents>();
            this.Invoice = new HashSet<Invoice>();
            this.InvoiceReceipt = new HashSet<InvoiceReceipt>();
            this.Payment = new HashSet<Payment>();
        }
    
        public int VendorKey { get; set; }
        public string VendorID { get; set; }
        public string VendName { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> CreateUserKey { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<int> UpdateUserKey { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> UserKey { get; set; }
        public string CompanyID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CheckRequest> CheckRequest { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChkReqDetail> ChkReqDetail { get; set; }
        public virtual Company Company { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Documents> Documents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Invoice> Invoice { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvoiceReceipt> InvoiceReceipt { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payment> Payment { get; set; }
        public virtual Users Users { get; set; }
    }
}
namespace Proveedores_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Voucher
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Voucher()
        {
            this.ChkReqDetail = new HashSet<ChkReqDetail>();
        }
    
        public int VoucherKey { get; set; }
        public Nullable<int> Vendorkey { get; set; }
        public Nullable<int> UserKey { get; set; }
        public string CompanyID { get; set; }
        public string TranNo { get; set; }
        public string TranID { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> CreateuserKey { get; set; }
        public Nullable<System.DateTime> TranDate { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<bool> Cargado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChkReqDetail> ChkReqDetail { get; set; }
    }
}
