//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proveedores_Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PortalProveedoresEntities : DbContext
    {
        internal object tapAPILogValidacion;

        public PortalProveedoresEntities()
            : base("name=PortalProveedoresEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AccessLog> AccessLog { get; set; }
        public virtual DbSet<Applications> Applications { get; set; }
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<CheckRequest> CheckRequest { get; set; }
        public virtual DbSet<ChkReqDetail> ChkReqDetail { get; set; }
        public virtual DbSet<ChkReqFile> ChkReqFile { get; set; }
        public virtual DbSet<Company> Company { get; set; }
        public virtual DbSet<Documents> Documents { get; set; }
        public virtual DbSet<ErrorLog> ErrorLog { get; set; }
        public virtual DbSet<InvcRcptDetails> InvcRcptDetails { get; set; }
        public virtual DbSet<InvcRcptFile> InvcRcptFile { get; set; }
        public virtual DbSet<Invoice> Invoice { get; set; }
        public virtual DbSet<InvoiceLines> InvoiceLines { get; set; }
        public virtual DbSet<InvoiceReceipt> InvoiceReceipt { get; set; }
        public virtual DbSet<InvoiceTaxLine> InvoiceTaxLine { get; set; }
        public virtual DbSet<Memberships> Memberships { get; set; }
        public virtual DbSet<Payment> Payment { get; set; }
        public virtual DbSet<Profiles> Profiles { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<SettingsEmail> SettingsEmail { get; set; }
        public virtual DbSet<TypeFiles> TypeFiles { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<UsersInCompany> UsersInCompany { get; set; }
        public virtual DbSet<UsersInRoles> UsersInRoles { get; set; }
        public virtual DbSet<Vendors> Vendors { get; set; }
        public virtual DbSet<Voucher> Voucher { get; set; }
        public virtual DbSet<DocumentsFile> DocumentsFile { get; set; }
        public virtual DbSet<InvoiceFile> InvoiceFile { get; set; }
        public virtual DbSet<PaymentAppl> PaymentAppl { get; set; }
        public virtual DbSet<PaymentFile> PaymentFile { get; set; }
        public virtual DbSet<StatusDocs> StatusDocs { get; set; }
        public virtual DbSet<StatusUsers> StatusUsers { get; set; }
        public virtual DbSet<tapLFStatus> tapLFStatus { get; set; }
    }
}
